In [8]:
import pandas as pd

In [10]:
d=pd.read_csv("results.csv")
d

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
0,0,65,10,59,3,71,37,245,0,3
1,1,94,56,4,67,91,50,362,1,1
2,2,7,85,76,99,60,25,352,0,2
3,3,88,46,59,94,52,38,377,1,1
4,4,39,81,37,38,6,54,255,1,3
...,...,...,...,...,...,...,...,...,...,...
995,995,55,89,68,58,13,13,296,0,2
996,996,42,62,25,87,51,68,335,1,2
997,997,9,83,70,14,11,78,265,0,3
998,998,23,82,31,42,84,52,314,0,2
999,999,75,78,68,33,79,91,424,1,1

In [11]:
d.columns[d.isnull().any()]

Index([], dtype='object')

In [12]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   Hindi       1000 non-null   int64
 2   English     1000 non-null   int64
 3   Science     1000 non-null   int64
 4   Maths       1000 non-null   int64
 5   History     1000 non-null   int64
 6   Geograpgy   1000 non-null   int64
 7   Total       1000 non-null   int64
 8   Results     1000 non-null   int64
 9   Div         1000 non-null   int64
dtypes: int64(10)
memory usage: 78.3 KB

In [13]:
nd = d.select_dtypes(include=["int64","int64"])
nd

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
0,0,65,10,59,3,71,37,245,0,3
1,1,94,56,4,67,91,50,362,1,1
2,2,7,85,76,99,60,25,352,0,2
3,3,88,46,59,94,52,38,377,1,1
4,4,39,81,37,38,6,54,255,1,3
...,...,...,...,...,...,...,...,...,...,...
995,995,55,89,68,58,13,13,296,0,2
996,996,42,62,25,87,51,68,335,1,2
997,997,9,83,70,14,11,78,265,0,3
998,998,23,82,31,42,84,52,314,0,2
999,999,75,78,68,33,79,91,424,1,1

In [14]:
nd.corr()

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
Unnamed: 0,1.000000,-0.013624,0.022504,0.046363,0.075332,-0.006175,0.005960,0.051777,0.001772,0.006430
Hindi,-0.013624,1.000000,0.036455,0.037616,0.041240,-0.024652,-0.064189,0.420384,0.273680,-0.081679
English,0.022504,0.036455,1.000000,-0.022411,-0.011269,-0.001812,0.052253,0.411884,0.255056,-0.067873
Science,0.046363,0.037616,-0.022411,1.000000,0.056314,0.005605,0.028846,0.445319,0.276698,-0.068866
Maths,0.075332,0.041240,-0.011269,0.056314,1.000000,0.011525,-0.001140,0.437754,0.285308,-0.110058
History,-0.006175,-0.024652,-0.001812,0.005605,0.011525,1.000000,-0.022318,0.387443,0.238060,-0.081133
Geograpgy,0.005960,-0.064189,0.052253,0.028846,-0.001140,-0.022318,1.000000,0.395791,0.226652,-0.082183
Total,0.051777,0.420384,0.411884,0.445319,0.437754,0.387443,0.395791,1.000000,0.622658,-0.196862
Results,0.001772,0.273680,0.255056,0.276698,0.285308,0.238060,0.226652,0.622658,1.000000,-0.258817
Div,0.006430,-0.081679,-0.067873,-0.068866,-0.110058,-0.081133,-0.082183,-0.196862,-0.258817,1.000000

In [16]:
x=nd[["Total"]]
y=nd["Div"]
x

     Total
0      245
1      362
2      352
3      377
4      255
..     ...
995    296
996    335
997    265
998    314
999    424

[1000 rows x 1 columns]

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=32)
x_test

     Total
632    246
687    348
833    266
182    222
831    254
..     ...
258    365
118    443
279    390
458    376
301    175

[200 rows x 1 columns]

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [20]:
y_pred=lr.predict(x_test)
y_pred

array([3, 2, 3, 3, 3, 0, 1, 1, 3, 2, 1, 2, 1, 2, 3, 1, 2, 2, 3, 2, 0, 2,
       2, 2, 2, 2, 3, 3, 2, 1, 2, 2, 2, 3, 2, 0, 3, 1, 2, 1, 1, 2, 1, 2,
       0, 2, 2, 1, 0, 1, 2, 2, 2, 1, 0, 1, 2, 1, 2, 2, 1, 2, 1, 2, 0, 1,
       1, 2, 1, 0, 1, 2, 1, 2, 0, 2, 2, 0, 0, 2, 1, 2, 3, 2, 2, 2, 1, 3,
       1, 3, 1, 1, 0, 3, 2, 3, 2, 2, 1, 2, 2, 0, 1, 1, 1, 2, 3, 3, 2, 3,
       2, 0, 2, 3, 3, 2, 1, 3, 3, 3, 1, 2, 1, 0, 2, 3, 3, 2, 2, 3, 2, 1,
       2, 3, 2, 2, 2, 3, 1, 1, 2, 2, 1, 2, 3, 1, 2, 3, 1, 2, 2, 2, 2, 3,
       3, 2, 2, 3, 2, 2, 3, 1, 2, 1, 2, 3, 1, 3, 2, 3, 0, 2, 2, 2, 2, 3,
       3, 3, 2, 2, 2, 3, 3, 3, 3, 2, 0, 3, 2, 1, 3, 2, 0, 2, 3, 1, 1, 1,
       1, 0])

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
accuracy_score(y_test,y_pred)

0.98